### PR TITLE
New badges 2018-11-06 and on

### PR DESCRIPTION
**Pull request by hypesystem**
@Arth101 missing some resizing on images. Would be neat if you could do those :smile:

### CODE REVIEW

**Comment by hypesystem** [comment]
More to come, but let's get these merged first :smile:

**Comment by Arth101** [comment]
Onnit. Kommer i løbet af en time :)

**Comment by Arth101** [comment]
Images compressed and cropped!

**Comment by hypesystem** [comment]
@Arth101 Spejdernisse-mærkets billede er stadig bad 😦

**Pull request merged**
