### PR TITLE
Add new header (standalone version)

### PR DESCRIPTION
**Pull request by Arth101**
Updated the header and nav, and tune other sites to fit the new stuff.
localhost-4000- 1

### CODE REVIEW

**Comment by hypesystem** [comment]
almost good to merge, but needs fix on shop page (when searching): 

billede

**Comment by Arth101** [comment]
Ahh, den fejl er der også i produktion kan jeg se. Gotta fix

**Comment by Arth101** [comment]
Så er det fikset:
https://new-nav-standalone--maerkelex.netlify.com/shop

**Comment by hypesystem** [comment]
It looks so good my main buddy-boy imma merge it real quick yo

**Pull request merged**
